trainData <- read.table("~/Desktop/X_train.txt")
dim(trainData) 
head(trainData)
trainLabel <- read.table("~/Desktop/y_train.txt")
table(trainLabel)
trainSubject <- read.table("~/Desktop/subject_train.txt")
testData <- read.table("~/Desktop/X_test.txt")
dim(testData) 
testLabel <- read.table("~/Desktop/y_test.txt") 
table(testLabel) 
testSubject <- read.table("~/Desktop/subject_test.txt")
joinData <- rbind(trainData, testData)
dim(joinData) 
joinLabel <- rbind(trainLabel, testLabel)
dim(joinLabel)
joinSubject <- rbind(trainSubject, testSubject)
dim(joinSubject)
